spring:
  cloud:
    gateway:
      globalcors: # 全局的跨域处理
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*" # 允许哪些网站的跨域请求
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 3600000 # 这次跨域检测的有效期
        add-to-simple-url-handler-mapping: true
      routes: # 网关路由配置
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
        - id: service-video
          uri: lb://service-video
          predicates:
            - Path=/api/video/**
        - id: service-interact
          uri: lb://service-interact
          predicates:
            - Path=/api/interact/**
        - id: service-search
          uri: lb://service-search
          predicates:
            - Path=/api/search/**
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"