# 配置mybatis
mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #标准输出
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

redisson:
  address: redis://14.103.139.54:6379

server:
  port: 8086   # 服务端口

spring:
  datasource:
    url: jdbc:mysql://14.103.139.54:3306/bluewhale?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  redis:
    host: 14.103.139.54
    port: 6379
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 20
        max-wait: 5000
  rabbitmq:
    host: 14.103.139.54
    port: 5672
    virtual-host: /bluewhale
    username: root
    password: 123456
  data:
    mongodb:
      uri: mongodb://admin:123456@14.103.139.54:27017/bluewhale?authSource=admin
