# 配置mybatis
mybatis:
  # mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #标准输出
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


server:
  port: 8083   # 服务端口

spring:
  datasource:
    url: jdbc:mysql://14.103.139.54:3306/bluewhale?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  redis:
    host: 14.103.139.54
    port: 6379
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 20
        max-wait: 5000
  rabbitmq:
    host: 14.103.139.54
    port: 5672
    virtual-host: /bluewhale
    username: root
    password: 123456
    listener:
      simple:
        prefetch: 1 # 每次拉取的消息数量,处理完
        concurrency: 10 # 消费者并发数量,处理完
        max-concurrency: 100 # 消费者最大并发数量

        acknowledgement-mode: auto # 消息确认模式,auto自动确认,manual手动确认,none不确认
        retry:
          enabled: true # 开启重试
          max-attempts: 3 # 最大重试次数
          initial-interval: 1000 # 重试间隔时间
          mutiplier: 1 # 重试间隔时间倍数
elasticsearch:
  host: 14.103.139.54
  port: 9200